type: object
required:
  - id
  - name
  - price
properties:
  id:
    type: string
    format: uuid
    example: 01962bb2-db70-7f03-8820-6e5f4e948515
  name:
    type: string
    example: Banane plantin
  description:
    type: string
    example: Banane plantin produite par des agriculteurs guinéens
  imageUrl:
    type: string
    example: http://localhost:8080/api/images/products/plantain.png
  price:
    type: number
    format: float
    example: 45.0
  productType:
    type: string
    enum:
      - DISH
      - BEVERAGE
      - APPETIZER
      - DESSERT
    example: DISH
