openapi: 3.1.0
info:
  title: Dineroo Restaurant API
  version: v1
  contact:
    name: API Management Team
    url: https://dineroo.api.com
    email: dineroo.cfg@gmail.com

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /v1/restaurants:
    get:
      tags:
        - Restaurant Management
      summary: Retrieve all restaurants
      operationId: getRestaurants
      responses:
        "200":
          description: A list of available restaurants
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantCollection"

  /v1/restaurants/{restaurantId}:
    get:
      tags:
        - Restaurant Management
      summary: Retrieve a specific restaurant by ID
      operationId: getRestaurantById
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Restaurant details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"

  /v1/restaurants/{restaurantId}/menus/{menuId}:
    get:
      tags:
        - Restaurant Management
      summary: Retrieve a menu by restaurant and menu ID
      operationId: getMenuById
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: menuId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Menu details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Menu"

components:
  schemas:
    RestaurantCollection:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/RestaurantItem"

    RestaurantItem:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: 01962bb7-8dc0-77fe-827e-61c22cea6028
        name:
          type: string
          example: Gastro africa
        address:
          type: string
          example: Petit simbaya
        description:
          type: string
          example: Restaurant de produits locaux
        imageUrl:
          type: string
          example: "path/to/image.png"

    Restaurant:
      type: object
      required:
        - id
        - name
        - menus
        - products
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Nomad
        address:
          type: string
          example: Koloma carrefour
        description:
          type: string
          example: Good restaurant with delicious dishes
        imageUrl:
          type: string
          example: "path/to/image.png"
        menus:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Menu"
        products:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Product"

    Menu:
      type: object
      required:
        - id
        - name
        - productIds
        - price
      properties:
        id:
          type: string
          format: uuid
          example: 01962bb2-06a5-7154-9c66-cbb401865214
        name:
          type: string
          example: Akieke au poisson
        description:
          type: string
          example: "Restaurant proposal "
        imageUrl:
          type: string
          example: "http://localhost:8080/api/images/restaurant/favela.png"
        price:
          type: number
          format: float
          example: 26.9

    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          format: uuid
          example: 01962bb2-db70-7f03-8820-6e5f4e948515
        name:
          type: string
          example: Banane plantin
        description:
          type: string
          example: Banane plantin produit par les agriculteurs africains
        imageUrl:
          type: string
          example: "path/to/image.png"
        price:
          type: number
          format: float
          example: 45.0

tags:
  - name: Restaurant Management
    description: Endpoints for managing restaurants, menus, and products
