name: Bundle and Deploy API Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/openapi/**'
      - 'package.json'
      - '.github/workflows/bundle-docs.yml'

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Bundle OpenAPI docs
        run: npm run bundle-docs

      - name: Commit and push updated bundle (if needed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/openapi/bundle.yaml
          git diff --staged --quiet || (git commit -m "chore: update OpenAPI bundle" && git push)
